# Generated by Django 5.2.4 on 2025-07-11 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('friendly', 'Friendly'), ('strict', 'Strict'), ('humorous', 'Humorous'), ('encouraging', 'Encouraging')], max_length=50, unique=True)),
                ('system_prompt', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'tutor_personas',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('retrieved_content', models.JSONField(default=list)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.tutorpersona')),
            ],
            options={
                'db_table': 'question_answers',
            },
        ),
    ]
