# Generated by Django 5.2.4 on 2025-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorpersona',
            name='name',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('strict', 'Strict'), ('humorous', 'Humorous'), ('encouraging', 'Encouraging')], max_length=50),
        ),
    ]
